#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

[ -f .env ] || { echo "no .env — copy .env.example to .env first"; exit 1; }
set -a; source .env; set +a

{
  echo "# generated by start.sh from .env — do not edit"
  echo "services:"
  echo "  csv-analyst:"
  echo "    ports:"
  echo "      - \"${PORT:-41733}:41733\""
  if [ -n "${CSV_SOURCES:-}" ]; then
    echo "    volumes:"
    IFS=',' read -ra entries <<<"$CSV_SOURCES"
    for e in "${entries[@]}"; do
      e="${e#"${e%%[![:space:]]*}"}"          # trim leading space
      # "path:name" — the name is optional, and without it the mount is named
      # after the directory (not the whole host path, which would nest under /mnt)
      if [[ "$e" == *:* ]]; then
        host="${e%:*}" name="${e##*:}"
      else
        host="$e" name="$(basename "$e")"
      fi
      name="${name//\//_}"
      [ -n "$name" ] || name="$(basename "$host")"
      [ -d "$host" ] || { echo "warning: skipping missing dir: $host" >&2; continue; }
      echo "      - ${host}:/mnt/${name}:ro"
    done
  fi
} > docker-compose.override.yml

docker compose up -d --build
